/**
 * exports.js — Multiple output format generators
 *
 * Converts analyzed design data into:
 * - Tailwind CSS config
 * - CSS custom properties file
 * - Style Dictionary JSON
 * - Figma Tokens JSON
 *
 * For educational and experimental purposes only.
 */

// ═══════════════════════════════════════════════════════════════
// Tailwind Config
// ═══════════════════════════════════════════════════════════════

export function toTailwindConfig(data) {
  const colors = {};
  for (const c of data.colors) {
    const name = c.role.replace(/[^a-zA-Z0-9]/g, "-");
    colors[name] = c.hex;
  }

  const fontSize = {};
  for (const [level, h] of Object.entries(data.headingMap)) {
    fontSize[level] = [h.size, { lineHeight: h.lineHeight, letterSpacing: h.letterSpacing || "normal", fontWeight: h.weight }];
  }
  for (const s of data.typeSizes.slice(0, 8)) {
    const label = Math.round(s.px);
    if (!fontSize[`${label}`]) fontSize[`${label}`] = s.size;
  }

  const spacing = {};
  for (const s of data.spacingScale) {
    const key = Math.round(s.px);
    spacing[`${key}`] = s.value;
  }

  const borderRadius = {};
  for (let i = 0; i < data.radii.length; i++) {
    const label = i === 0 ? "DEFAULT" : data.radii[i].value.replace(/px/g, "");
    borderRadius[label] = data.radii[i].value;
  }

  const boxShadow = {};
  for (const s of data.shadows) {
    boxShadow[s.level] = s.value;
  }

  const fontFamily = {};
  for (const f of data.fonts) {
    fontFamily[f.role] = f.families;
  }

  const config = {
    theme: {
      extend: {
        colors,
        fontFamily,
        fontSize,
        spacing,
        borderRadius,
        boxShadow,
      },
    },
  };

  if (data.breakpointList.length > 0) {
    config.theme.extend.screens = {};
    for (const bp of data.breakpointList) {
      config.theme.extend.screens[`${bp.px}`] = `${bp.px}px`;
    }
  }

  return `/** @type {import('tailwindcss').Config} */
// Generated by designsnap — educational and experimental use only
// Source: ${data.url}

export default ${JSON.stringify(config, null, 2)}
`;
}

// ═══════════════════════════════════════════════════════════════
// CSS Custom Properties
// ═══════════════════════════════════════════════════════════════

export function toCSSVariables(data) {
  const lines = [
    "/* Generated by designsnap — educational and experimental use only */",
    `/* Source: ${data.url} */`,
    "",
    ":root {",
    "  /* Colors */",
  ];

  for (const c of data.colors) {
    const name = c.role.replace(/[^a-zA-Z0-9]/g, "-");
    lines.push(`  --color-${name}: ${c.hex};`);
  }

  lines.push("", "  /* Typography */");
  for (const f of data.fonts) {
    lines.push(`  --font-${f.role}: ${f.families.join(", ")};`);
  }

  if (data.scaleRatio) {
    lines.push(`  --type-scale-ratio: ${data.scaleRatio.detected};`);
  }

  for (const [level, h] of Object.entries(data.headingMap).sort()) {
    lines.push(`  --${level}-size: ${h.size};`);
    lines.push(`  --${level}-weight: ${h.weight};`);
    lines.push(`  --${level}-line-height: ${h.lineHeight};`);
  }

  lines.push("", "  /* Spacing */");
  if (data.gridSystem) lines.push(`  --spacing-unit: ${data.gridSystem.base}px;`);
  for (const s of data.spacingScale) {
    const key = Math.round(s.px);
    lines.push(`  --space-${key}: ${s.value};`);
  }

  lines.push("", "  /* Border Radius */");
  for (let i = 0; i < data.radii.length; i++) {
    const label = i === 0 ? "default" : `${i + 1}`;
    lines.push(`  --radius-${label}: ${data.radii[i].value};`);
  }

  lines.push("", "  /* Shadows */");
  for (const s of data.shadows) {
    lines.push(`  --shadow-${s.level}: ${s.value};`);
  }

  if (data.opacityValues.length > 0) {
    lines.push("", "  /* Opacity */");
    for (const o of data.opacityValues) {
      const pct = Math.round(parseFloat(o.value) * 100);
      lines.push(`  --opacity-${pct}: ${o.value};`);
    }
  }

  if (data.motionSystem && Object.keys(data.motionSystem.durations).length > 0) {
    lines.push("", "  /* Motion */");
    const durations = Object.entries(data.motionSystem.durations).sort((a, b) => parseFloat(a[0]) - parseFloat(b[0]));
    for (const [dur, count] of durations) {
      const name = dur.replace(/[^a-zA-Z0-9]/g, "");
      lines.push(`  --duration-${name}: ${dur};`);
    }
    const easings = Object.entries(data.motionSystem.easings).sort((a, b) => b[1] - a[1]);
    for (const [ease] of easings.slice(0, 4)) {
      const name = ease.replace(/[^a-zA-Z0-9]/g, "-").replace(/-+/g, "-");
      lines.push(`  --ease-${name}: ${ease};`);
    }
  }

  lines.push("}", "");

  // Dark mode
  if (data.darkModeData?.vars) {
    lines.push("@media (prefers-color-scheme: dark) {");
    lines.push("  :root {");
    for (const [k, v] of Object.entries(data.darkModeData.vars)) {
      lines.push(`    ${k}: ${v};`);
    }
    lines.push("  }");
    lines.push("}", "");
  }

  return lines.join("\n");
}

// ═══════════════════════════════════════════════════════════════
// Style Dictionary JSON
// ═══════════════════════════════════════════════════════════════

export function toStyleDictionary(data) {
  const tokens = {
    $description: `Design tokens extracted from ${data.url}. For educational and experimental purposes only.`,
    color: {},
    font: {},
    size: {},
    space: {},
    radius: {},
    shadow: {},
    opacity: {},
    motion: {},
  };

  // Colors
  for (const c of data.colors) {
    const name = c.role.replace(/[^a-zA-Z0-9]/g, "-");
    tokens.color[name] = {
      $value: c.hex,
      $type: "color",
      $description: `${c.role} — ${c.count} uses`,
    };
  }

  // Fonts
  for (const f of data.fonts) {
    tokens.font[f.role] = {
      $value: f.families,
      $type: "fontFamily",
    };
  }

  // Type sizes
  for (const [level, h] of Object.entries(data.headingMap).sort()) {
    tokens.size[level] = {
      fontSize: { $value: h.size, $type: "dimension" },
      fontWeight: { $value: h.weight, $type: "fontWeight" },
      lineHeight: { $value: h.lineHeight, $type: "dimension" },
    };
  }

  // Spacing
  for (const s of data.spacingScale) {
    const key = Math.round(s.px);
    tokens.space[`${key}`] = { $value: s.value, $type: "dimension" };
  }

  // Radius
  for (let i = 0; i < data.radii.length; i++) {
    tokens.radius[`${i + 1}`] = { $value: data.radii[i].value, $type: "dimension" };
  }

  // Shadows
  for (const s of data.shadows) {
    tokens.shadow[s.level] = { $value: s.value, $type: "shadow" };
  }

  // Opacity
  for (const o of data.opacityValues) {
    const pct = Math.round(parseFloat(o.value) * 100);
    tokens.opacity[`${pct}`] = { $value: o.value, $type: "number" };
  }

  // Motion
  if (data.motionSystem) {
    for (const [dur] of Object.entries(data.motionSystem.durations).sort((a, b) => parseFloat(a[0]) - parseFloat(b[0]))) {
      const name = dur.replace(/[^a-zA-Z0-9]/g, "");
      tokens.motion[`duration-${name}`] = { $value: dur, $type: "duration" };
    }
  }

  return JSON.stringify(tokens, null, 2);
}

// ═══════════════════════════════════════════════════════════════
// Figma Tokens JSON (compatible with Tokens Studio)
// ═══════════════════════════════════════════════════════════════

export function toFigmaTokens(data) {
  const tokens = {
    global: {
      colors: {},
      typography: {},
      spacing: {},
      borderRadius: {},
      boxShadow: {},
      opacity: {},
    },
  };

  for (const c of data.colors) {
    const name = c.role.replace(/[^a-zA-Z0-9]/g, "-");
    tokens.global.colors[name] = { value: c.hex, type: "color" };
  }

  for (const f of data.fonts) {
    tokens.global.typography[f.role] = {
      value: { fontFamily: f.families[0] || "system-ui" },
      type: "typography",
    };
  }

  for (const s of data.spacingScale) {
    const key = Math.round(s.px);
    tokens.global.spacing[`${key}`] = { value: s.value, type: "spacing" };
  }

  for (let i = 0; i < data.radii.length; i++) {
    tokens.global.borderRadius[`${i + 1}`] = { value: data.radii[i].value, type: "borderRadius" };
  }

  for (const s of data.shadows) {
    tokens.global.boxShadow[s.level] = { value: s.value, type: "boxShadow" };
  }

  return JSON.stringify(tokens, null, 2);
}
